// <auto-generated />
using System;
using Idea.Cookbook;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Idea.Cookbook.Migrations
{
    [DbContext(typeof(CookbookModelContext))]
    partial class CookbookModelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Idea.Cookbook.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<float?>("Amount");

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("CreatedBy");

                    b.Property<string>("Name");

                    b.Property<Guid?>("RecipeId");

                    b.Property<DateTime?>("Removed");

                    b.Property<Guid>("RemovedBy");

                    b.Property<Guid>("UnitId");

                    b.Property<Guid?>("UnitId1");

                    b.Property<DateTime?>("Updated");

                    b.Property<Guid>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("Removed");

                    b.HasIndex("UnitId");

                    b.HasIndex("UnitId1");

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("Idea.Cookbook.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("CreatedBy");

                    b.Property<string>("Directions");

                    b.Property<string>("Name");

                    b.Property<DateTime?>("Removed");

                    b.Property<Guid>("RemovedBy");

                    b.Property<DateTime?>("Updated");

                    b.Property<Guid>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("Removed");

                    b.ToTable("Recipe");
                });

            modelBuilder.Entity("Idea.Cookbook.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("CreatedBy");

                    b.Property<string>("Name");

                    b.Property<DateTime?>("Removed");

                    b.Property<Guid>("RemovedBy");

                    b.Property<string>("Symbol");

                    b.Property<DateTime?>("Updated");

                    b.Property<Guid>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("Removed");

                    b.ToTable("Unit");

                    b.HasData(
                        new { Id = new Guid("011dbeeb-895d-4bde-b651-91ccf204b9fa"), Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"), Name = "Kilogram", RemovedBy = new Guid("00000000-0000-0000-0000-000000000000"), Symbol = "Kg", UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000") },
                        new { Id = new Guid("4ec94793-cc7f-45cc-a06a-05c65f0c2d58"), Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"), Name = "Gram", RemovedBy = new Guid("00000000-0000-0000-0000-000000000000"), Symbol = "g", UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000") },
                        new { Id = new Guid("2611bf28-869e-4fdb-84e7-6b418abb3cca"), Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"), Name = "Liter", RemovedBy = new Guid("00000000-0000-0000-0000-000000000000"), Symbol = "l", UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000") }
                    );
                });

            modelBuilder.Entity("Idea.Cookbook.Entities.Ingredient", b =>
                {
                    b.HasOne("Idea.Cookbook.Entities.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId");

                    b.HasOne("Idea.Cookbook.Entities.Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Idea.Cookbook.Entities.Unit", "Unit")
                        .WithMany("Ingredients")
                        .HasForeignKey("UnitId1");
                });
#pragma warning restore 612, 618
        }
    }
}
